export enum FileCategoryEnum {
    CAPITAL_REPAIR_PROJECT = 'CAPITAL_REPAIR_PROJECT',
    DESIGN_DOCUMENTATION = 'DESIGN_DOCUMENTATION',
    INSPECTION_RESULT = 'INSPECTION_RESULT',
    TECHNICAL_PASSPORT = 'TECHNICAL_PASSPORT',
}
