""" -auto

Revision ID: 85a1263d8e8c
Revises: c6164a604c1f
Create Date: 2025-08-20 23:40:41.902600+03:00

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85a1263d8e8c"
down_revision: Union[str, None] = "c6164a604c1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "house",
        sa.Column(
            "supply_systems_major_repair_year",
            sa.Integer(),
            nullable=True,
            comment="Год проведения последнего капитального ремонта",
        ),
    )
    op.alter_column(
        "house",
        "number_of_inputs",
        existing_type=sa.INTEGER(),
        comment="Количество вводов системы электроснабжения, ед",
        existing_comment="Количество вводов в дом, ед.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "house",
        "number_of_inputs",
        existing_type=sa.INTEGER(),
        comment="Количество вводов в дом, ед.",
        existing_comment="Количество вводов системы электроснабжения, ед",
        existing_nullable=True,
    )
    op.drop_column("house", "supply_systems_major_repair_year")
    # ### end Alembic commands ###
