""" -auto

Revision ID: 6540518ec31f
Revises: 9ab14ea79307
Create Date: 2025-08-20 00:47:08.343312+03:00

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6540518ec31f"
down_revision: Union[str, None] = "9ab14ea79307"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "house",
        sa.Column(
            "cadastral_number", sa.String(), nullable=True, comment="Кадастровый номер"
        ),
    )
    op.add_column(
        "house",
        sa.Column("classifier_code", sa.String(), nullable=True, comment="Код ОКТМО"),
    )
    op.add_column(
        "house",
        sa.Column(
            "water_system_valve_wear",
            sa.Float(),
            nullable=True,
            comment="Физический износ запорной арматуры системы отопления",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("house", "water_system_valve_wear")
    op.drop_column("house", "classifier_code")
    op.drop_column("house", "cadastral_number")
    # ### end Alembic commands ###
