""" -auto

Revision ID: 273961aa8143
Revises: 944f7d8770ed
Create Date: 2025-08-21 16:42:47.962712+03:00

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "273961aa8143"
down_revision: Union[str, None] = "944f7d8770ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "house",
        "building_wear_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_comment="Дата установления износа",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "house",
        "building_wear_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_comment="Дата установления износа",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
