""" -auto

Revision ID: 0e234c65b086
Revises: 273961aa8143
Create Date: 2025-08-21 16:49:55.035967+03:00

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e234c65b086"
down_revision: Union[str, None] = "273961aa8143"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("house", "supply_systems_major_repair_year")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "house",
        sa.Column(
            "supply_systems_major_repair_year",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Год проведения последнего капитального ремонта",
        ),
    )
    # ### end Alembic commands ###
