""" -auto

Revision ID: 944f7d8770ed
Revises: 85a1263d8e8c
Create Date: 2025-08-20 23:48:15.198192+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944f7d8770ed'
down_revision: Union[str, None] = '85a1263d8e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('supply_systems_number', sa.Integer(), nullable=True, comment='Количество вводов системы электроснабжения, ед'))
    op.alter_column('house', 'number_of_inputs',
               existing_type=sa.INTEGER(),
               comment='Количество вводов в дом, ед',
               existing_comment='Количество вводов системы электроснабжения, ед',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('house', 'number_of_inputs',
               existing_type=sa.INTEGER(),
               comment='Количество вводов системы электроснабжения, ед',
               existing_comment='Количество вводов в дом, ед',
               existing_nullable=True)
    op.drop_column('house', 'supply_systems_number')
    # ### end Alembic commands ###
